return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")
		configs.setup({
			ensure_installed = {
				"c",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"javascript",
				"html",
				"python",
				"bash",
				"dockerfile",
				"go",
				"htmldjango",
				"http",
				"jq",
				"json",
				"markdown",
				"perl",
				"php",
				"rasi",
				"rust",
				"sql",
				"tmux",
				"toml",
				"vue",
				"xml",
				"yaml",
				"zig",
			},
			-- sync_install = false,
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
