import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font] 
size = 20.0

[font.normal] 
family = "JetbrainsMono Nerd Font" 
style = "Regular" 

[window] 
opacity = 1
blur = true

[window.padding] 
x = 15 
y = 15

